# Use AWS Lambda Container base image
FROM public.ecr.aws/lambda/python:3.9

# Required for Spotipy
ARG SPOTIPY_CLIENT_ID
ARG SPOTIPY_CLIENT_SECRET
ARG SPOTIPY_REDIRECT_URI
ARG SPOTIFY_MARKET
ARG BACKIFY_S3_BUCKET
ARG BACKUP_S3_BUCKET_FOLDER
ARG TOKENS_CACHE_S3_BUCKET_FOLDER

ENV SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
ENV SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
ENV SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
ENV SPOTIFY_MARKET=${SPOTIFY_MARKET}
ENV BACKIFY_S3_BUCKET=${BACKIFY_S3_BUCKET}
ENV BACKUP_S3_BUCKET_FOLDER=${BACKUP_S3_BUCKET_FOLDER}
ENV TOKENS_CACHE_S3_BUCKET_FOLDER=${TOKENS_CACHE_S3_BUCKET_FOLDER}

COPY Pipfile .
COPY Pipfile.lock .

RUN pip install -U pipenv
RUN pipenv requirements > requirements.txt
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY backify ${LAMBDA_TASK_ROOT}/backify

CMD [ "backify.main.handler" ]
